#!/usr/bin/env bash
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
BOLD='\033[1m'
NC='\033[0m'

echo -e "${BOLD}prs installer${NC}\n"

# Verify dependencies
echo "Checking dependencies..."
missing=()

if ! command -v gh &>/dev/null; then
    missing+=("gh (GitHub CLI)")
fi

if ! command -v bk &>/dev/null; then
    missing+=("bk (Buildkite CLI)")
fi

if ! command -v jq &>/dev/null; then
    missing+=("jq")
fi

if [[ ${#missing[@]} -gt 0 ]]; then
    echo -e "${RED}Missing dependencies:${NC}"
    for dep in "${missing[@]}"; do
        echo "  - $dep"
    done
    echo ""
    if [[ " ${missing[*]} " == *"bk"* ]]; then
        echo "Install bk (Buildkite CLI) from:"
        echo "  https://buildkite.com/docs/platform/cli/installation"
        echo ""
    fi
    echo "Install missing dependencies, then re-run this script."
    exit 1
fi

echo -e "${GREEN}✓${NC} All dependencies installed"

# Verify auth
echo -e "\nChecking authentication..."

if ! gh auth status &>/dev/null; then
    echo -e "${RED}✗${NC} GitHub CLI not authenticated. Run: gh auth login"
    exit 1
fi
echo -e "${GREEN}✓${NC} GitHub CLI authenticated"

if ! bk whoami &>/dev/null; then
    echo -e "${RED}✗${NC} Buildkite CLI not authenticated. Run: bk configure"
    echo ""
    echo "  You'll need an API token from:"
    echo "  https://buildkite.com/user/api-access-tokens"
    echo ""
    echo "  1. Required scopes: read_artifacts, read_builds, write_builds, read_build_logs, read_pipelines, graphql"
    echo "  2. Organization Access: MUST select your org!"
    exit 1
fi
echo -e "${GREEN}✓${NC} Buildkite CLI authenticated"

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Setup symlinks and PATH
echo ""
read -p "Create symlinks in ~/bin and add to PATH? [Y/n] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    mkdir -p ~/bin

    [[ -L ~/bin/prs ]] && rm ~/bin/prs
    ln -s "$SCRIPT_DIR/prs" ~/bin/prs

    [[ -L ~/bin/prs.d ]] && rm ~/bin/prs.d
    ln -s "$SCRIPT_DIR/prs.d" ~/bin/prs.d

    echo -e "${GREEN}✓${NC} Symlinks created in ~/bin"

    path_line='export PATH="$HOME/bin:$PATH"'
    if [[ ":$PATH:" != *":$HOME/bin:"* ]] && ! grep -q "$path_line" ~/.bashrc 2>/dev/null; then
        echo "$path_line" >> ~/.bashrc
        echo -e "${GREEN}✓${NC} Added ~/bin to PATH in ~/.bashrc"
    fi
fi

# Configure
echo -e "\n${BOLD}Configuration${NC}"
CONFIG_FILE="$SCRIPT_DIR/prs.d/config.local.sh"

if [[ -f "$CONFIG_FILE" ]]; then
    read -p "config.local.sh exists. Overwrite? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "\n${GREEN}Installation complete!${NC}"
        exit 0
    fi
fi

# Get GitHub username from gh if possible
default_gh_user=$(gh api user -q .login 2>/dev/null || echo "")

# Get Buildkite org slug from bk if possible
default_bk_org=$(bk whoami 2>/dev/null | jq -r '.organization_slug // empty' 2>/dev/null || echo "")

if [[ -n "$default_gh_user" ]]; then
    read -p "GitHub username: $default_gh_user - correct? [Y/n] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        read -p "GitHub username: " github_user
    else
        github_user="$default_gh_user"
    fi
else
    read -p "GitHub username: " github_user
fi

read -p "Branch prefix (e.g., firstname.lastname): " branch_user

read -p "Target repo (e.g., \"owner/repo\" from github.com/<owner>/<repo>): " prs_repo

if [[ -n "$default_bk_org" ]]; then
    read -p "Buildkite org slug: $default_bk_org - correct? [Y/n] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Nn]$ ]]; then
        read -p "Buildkite org slug: " bk_org
    else
        bk_org="$default_bk_org"
    fi
else
    read -p "Buildkite org slug: " bk_org
fi

# Set bk org globally so it works from any directory
sed -i "s/selected_org: .*/selected_org: $bk_org/" ~/.config/bk.yaml 2>/dev/null
echo -e "${GREEN}✓${NC} Buildkite org set to: $bk_org"

read -p "Buildkite pipeline (e.g., my-pipeline): " bk_pipeline
ci_context="buildkite/${bk_pipeline}"

# Optional: submodule repo
submodule_repo=""
echo ""
read -p "Do you have a submodule repo with paired PRs? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    read -p "Submodule repo (e.g., \"owner/repo\"): " submodule_repo
fi

# Write config
cat > "$CONFIG_FILE" << EOF
# Local configuration - generated by install.sh

export GITHUB_USER="$github_user"
export BRANCH_USER="$branch_user"
export PRS_REPO="$prs_repo"
export BK_ORG="$bk_org"
export PRS_CI_CHECK_CONTEXT="$ci_context"
EOF

if [[ -n "$submodule_repo" ]]; then
    echo "export PRS_SUBMODULE_REPO=\"$submodule_repo\"" >> "$CONFIG_FILE"
fi

echo -e "${GREEN}✓${NC} Config written to prs.d/config.local.sh"

# Optional: completion
echo ""
read -p "Enable bash tab completion? [Y/n] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    completion_line='source ~/bin/prs.d/completion.bash'
    if ! grep -q "$completion_line" ~/.bashrc 2>/dev/null; then
        echo "$completion_line" >> ~/.bashrc
        echo -e "${GREEN}✓${NC} Completion added to ~/.bashrc"
    else
        echo -e "${GREEN}✓${NC} Completion already in ~/.bashrc"
    fi
fi

echo -e "\n${GREEN}Installation complete!${NC}"
echo "Run 'source ~/.bashrc' then try:"
echo ""
echo "  prs                  # List your open PRs"
echo "  prs my_feature       # Show status of a PR"
echo "  prs -b my_feature    # Show build steps"
